
package frontend;

import backend.AdminRole;
import backend.Trainer;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author DELL
 */
public class ViewTrainersWindow extends javax.swing.JFrame {

    /**
     * Creates new form ViewTrainersWindow
     */
    AdminRoleWindow adminW;
    AdminRole adminRole;
    public ViewTrainersWindow(AdminRole adminRole, AdminRoleWindow adminW) {
        initComponents();
        this.adminW =adminW;
        this.adminRole = adminRole;
        trainersTable();
    }

    public void trainersTable(){
        ArrayList<Trainer> m = (ArrayList<Trainer>) adminRole.getListOfTrainers();
    DefaultTableModel t = (DefaultTableModel) trainerTable.getModel();
        for (int i = 0; i < m.size(); i++) {
            t.addRow(new Object[]{m.get(i).trainerId ,m.get(i).name,m.get(i).email,m.get(i).speciality,m.get(i).phoneNumber});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        trainerTable = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Trainers ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        trainerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Email", "Speciality", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(trainerTable);
        if (trainerTable.getColumnModel().getColumnCount() > 0) {
            trainerTable.getColumnModel().getColumn(0).setResizable(false);
            trainerTable.getColumnModel().getColumn(1).setResizable(false);
            trainerTable.getColumnModel().getColumn(2).setResizable(false);
            trainerTable.getColumnModel().getColumn(3).setResizable(false);
            trainerTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
           adminW.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trainerTable;
    // End of variables declaration//GEN-END:variables
}
