
package frontend;

import backend.MemberClassRegistration;
import backend.TrainerRole;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ViewRegistrationsWindow extends javax.swing.JFrame {

    TrainerRoleWindow trainerRoleWindow;
    TrainerRole trainerRole;
    public ViewRegistrationsWindow(TrainerRole trainerRole, TrainerRoleWindow trainerRoleWindow) {
        initComponents();
        this.trainerRole = trainerRole;
        this.trainerRoleWindow = trainerRoleWindow;
        registrationsTable();
    }
    public void registrationsTable(){
        ArrayList<MemberClassRegistration> m = (ArrayList<MemberClassRegistration>) trainerRole.getListOfRegistrations();
    DefaultTableModel t = (DefaultTableModel) registrationsTable.getModel();
        for (int i = 0; i < m.size(); i++) {
            t.addRow(new Object[]{m.get(i).memberID,m.get(i).classID,m.get(i).registrationDate , m.get(i).status});
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        registrationsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Registrations");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        registrationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Id", "Class Id", "Registration Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(registrationsTable);
        if (registrationsTable.getColumnModel().getColumnCount() > 0) {
            registrationsTable.getColumnModel().getColumn(0).setResizable(false);
            registrationsTable.getColumnModel().getColumn(1).setResizable(false);
            registrationsTable.getColumnModel().getColumn(2).setResizable(false);
            registrationsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        trainerRoleWindow.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable registrationsTable;
    // End of variables declaration//GEN-END:variables
}
